### ISSUE TITLE
Allow Fedora / CentOS accounts?

### ISSUE THREAD

**Issue by mattdm** [operate-first/community#109]
It'd be nice to get people from the Fedora community involved — after all, we've got a long history of operate-first in practice.

It would be awesome if people could authenticate using their Fedora accounts (which are shared with CentOS):

* GitHub accounts don't necessarily correspond to Fedora accounts (and there are surely cases where a GitHub account overlaps a Fedora account name of a different person). There may also be people who just do not wish to have or use a GitHub account. This will make it harder to do what I'd like for https://github.com/operate-first/support/issues/500
*  I'd like this to map as closely as possible to the production Fedora OpenShift, so migrating services from here to there (and being put into ansible playbooks, etc.) is easily automated
* It would be useful to be able to tie access, permissions, and resource limits to Fedora Account groups

**Comment by HumairAK** [comment]
> and there are surely cases where a GitHub account overlaps a Fedora account name of a different person 

Our openshift auth leverage github usernames currently as ocp user names. Would this not cause naming conflicts with existing users that share the same Fedora account names? 

@4n4nd @durandom  @larsks

**Comment by larsks** [comment]
@HumairAK @mattdm (hi!) It should be possible to do this, but there's absolutely going to be a question about how we identify accounts. Right now the github username == the openshift username, which obviously isn't a tenable model if we add additional, unrelated authentication sources.

We explicitly moved away from using email addresses as account identifiers for reason of privacy (@mattdm we currently manage group membership through YAML files in a public git repository), but if using email addresses as identifiers turns out to be the most effective solution we may want to re-think how we manage group membership.

I think we need to do a little additional research to figure out what our options are here.

**Comment by larsks** [comment]
It looks like KeyCloak has a mapper named "Username Template Importer" that will do what we want. The tooltip for the template says:

> Template to use to format the username to import.  Substitutions are enclosed in ${}.  For example: '${ALIAS}.${CLAIM.sub}'.  ALIAS is the provider alias.  CLAIM.<NAME> references an ID or Access token claim. 
The substitution can be converted to upper or lower case by appending |uppercase or |lowercase to the substituted value, e.g. '${CLAIM.sub | lowercase}

**Comment by larsks** [comment]
If we want usernames to look like `<name>@<provider>`, we would set the template for GitHub to `${CLAIM.login}@${ALIAS}`. I'm not sure what the IDP configuration would look like for Fedora. 

@mattdm, how do we go about getting a client id and secret for FAS so that we can test things out? The [documentation](https://fedoraproject.org/wiki/Infrastructure/Authentication) suggests that we can use `oidc-register` to register against `iddev.fedorainfracloud.org` for development credentials, but that host isn't responding.

**Comment by mattdm** [comment]
@larsks File a ticket at https://pagure.io/fedora-infrastructure/issues

Also, hi!!! :)

**Comment by larsks** [comment]
I've opened https://pagure.io/fedora-infrastructure/issue/10428 requesting development OIDC credentials.

**Comment by larsks** [comment]
This was closed upstream without resolution. We can pursue this in the future if people are feeling motivated.
