### ISSUE TITLE
convert this repo to a JupyterBook

### ISSUE THREAD

**Issue by durandom** [operate-first/community#112]
* `.md` files should not be moved around, keep them organized as now
* only add some example entries to the `_toc.yaml`
* setup same publishing pipeline as for the `/apps` repo
* with a `gh-pages` publish 
* bonus points for a netlify preview :) 

Tasks: 
- [x] add jbook configurations 
- [x] add github action for automated builds 
- [x] add netlify previews in prs

**Comment by quaid** [comment]
Context -- @durandom answered my last concerns and convinced me how to organize the community handbook side of content in parallel to the technical ops docs. It also is clear we can use Jupyter for the contributor-oriented content.

My thinking is this:
1. Either a contributor is going to make changes to the community handbook in the GH UI,
2. Or a contributor is going to checkout the repo and make changes in their fork locally.

In all cases, these end up as PRs that can go through an editorial review/check process (automated and/or manual).

So in the second case, it's expected there is a higher barrier for running the CLI of things. We do things like use Toolbox and standard tooling, and document ourselves, so we can support that with contributors.

For the first case, we have to make sure the web UI editing is first class. So that means in this case, I can edit the Jupyter Notebook contents directly via the GitHub UI (i.e., via a link on each page "Edit in GitHub") in my fork, and when I make a PR of those edits, the automation doesn't error because of missing CLI requirements such as `pre-commit` hooks.

And ultimately having a netlify preview of the change in the PR is fantastic. This allows us to bring in people with practically zero experience in GitHub and Jupyter, and have them able to write, edit, and publish using GitOps. :grin:

**Comment by durandom** [comment]
@HumairAK can you also add the GH workflows, so that the book is automagically published?

https://github.com/operate-first/apps/blob/master/.github/workflows/book.yml

**Comment by HumairAK** [comment]
netlify previews set up: https://github.com/operate-first/community/pull/119
