### ISSUE TITLE
YouTube permissions for multiple people to upload

### ISSUE THREAD

**Issue by quaid** [operate-first/community#173]
For meeting notes, etc.

**Comment by aakankshaduggal** [comment]
Hey @quaid, could you please let us know the email associated for the people who'd want to upload on youtube.

**Comment by quaid** [comment]
> Hey @quaid, could you please let us know the email associated for the people who'd want to upload on youtube.

Thanks, that would be a great solution to get us going today. We also need to know the process that one of us would follow to get posted live.

But we can also look from the beginning at how this can scale with our GItOps processes, e.g. what if we started with a YAML file with GitHub handles for each of the people who need to upload to YT? Even if the YAML isn't driving anything yet, we get the data out of an issue and into a repo?

(Feel free to tell me I'm silly or offer a better approach for what I'm trying to do, thanks!)

**Comment by aakankshaduggal** [comment]
@quaid 
We will have to grant access to your existing Google account on youtube to be able to post and interact with the operate first youtube channel. Yes, a YAML or a document that stores every authorized user's **email** address because we probably need that to link to the youtube account instead of a Github handle. 

cc- @oindrillac please correct me if I am wrong. Is this the right set of action items we would require to add a user to operate first youtube account?
