### ISSUE TITLE
OpenTelemetry onboarding facilitation

### ISSUE THREAD

**Issue by quaid** [operate-first/community#83]
Connect together @sallyom with appropriate people and processes to start discussions and planning to bring OpenTelemetry to the Op1st community cloud.

Vision includes:
* The project will run latest upstream code with experimental features enabled.
* Open source devs can tap into the experimental features, e.g. OpenTelemetry Tracing enabled `etcd`, then use the API server to tie that to their own code so they can get an end-to-end trace for the time of a request (for example.)
* Roadmap should include having a way to use GitOps to provide granular control over which experimental feature is enabled for which environment.

**Comment by sallyom** [comment]
/remove-lifecycle stale

I'm planning on picking this back up

**Comment by quaid** [comment]
@sallyom are you still interested in working on this?

**Comment by sallyom** [comment]
yes, I am! The goal has shifted to installing Jaeger  + KSpan rather than enabling OTel in Kube/Etcd/CRIO  - due to the fact that these will not be exposed features in OpenShift in the current release. 
See here: https://github.com/operate-first/support/issues/491#issuecomment-1083069526  for current work
