### ISSUE TITLE
Existing Public Calendar for Events?

### ISSUE THREAD

**Issue by MichaelClifford** [operate-first/community#92]
I will be starting to host a monthly meetup for the opf data science community and was wondering if there is an existing public google calendar where I can add the recurring event and manage invites. If so, how do I access it and get my event added? If not, what is the best course of action to have one made? Let me know, thanks!

**Comment by HumairAK** [comment]
/remove-lifecycle stale

@quaid can you add @MichaelClifford to the public calendar (maybe we ought to add docs for whom/how/what one needs to do to get access or request events be added to the public calendar)

**Comment by quaid** [comment]
Can you make an issue for each of those at operate-first/community-handhook/ ? There is a template for Doc Needed.

We had the kickoff planning Contrib_X Docs WG this morning and agreed to use the project board for the Handbook.

**Comment by schwesig** [comment]
/close
will be worked on on in the created user stories above

how to create calendar entries
https://github.com/operate-first/community-handbook/issues/32

publish the complete calendar, e.g. just via a link on the website?
https://github.com/operate-first/community-handbook/issues/33

best practice on how to add / create meetings for the invites (afaik, we should use RH meetings, because recording)
https://github.com/operate-first/community-handbook/issues/34
